import type { CanvasNode, LayoutAlignment, LayoutDistribution } from '../../types/editor'
import { ancestorIds } from '../scene/sceneGraph'

const round=(value:number)=>Math.round(value*100)/100
const pads=(frame:CanvasNode)=>({top:frame.layout?.paddingTop??frame.layout?.padding??0,right:frame.layout?.paddingRight??frame.layout?.padding??0,bottom:frame.layout?.paddingBottom??frame.layout?.padding??0,left:frame.layout?.paddingLeft??frame.layout?.padding??0})

export function applyAutoLayout(objects:Record<string,CanvasNode>,order:string[],frameId:string):Record<string,CanvasNode> {
  const frame=objects[frameId]
  if(!frame?.layout)return objects
  const next={...objects},layout=frame.layout,padding=pads(frame),children=order.map((id)=>next[id]).filter((node):node is CanvasNode=>!!node&&node.parentId===frameId&&node.visible&&node.layoutPosition!=='absolute')
  if(!children.length)return next
  const innerWidth=Math.max(0,frame.width-padding.left-padding.right),innerHeight=Math.max(0,frame.height-padding.top-padding.bottom),gap=Math.max(0,layout.gap),align=layout.align??'start',distribution=layout.distribution??'start'
  for(const child of children){let width=child.width,height=child.height;if(child.widthMode==='percent')width=innerWidth*Math.max(0,child.widthPercent??100)/100;if(child.heightMode==='percent')height=innerHeight*Math.max(0,child.heightPercent??100)/100;if(child.widthMode==='fill'&&(layout.direction==='vertical'||layout.direction==='grid'))width=innerWidth;if(child.heightMode==='fill'&&layout.direction==='horizontal')height=innerHeight;next[child.id]={...child,width:Math.max(1,round(width)),height:Math.max(1,round(height))}}
  if(layout.direction==='grid')return applyGrid(next,children.map((child)=>next[child.id]),frame,padding,gap,align)
  const horizontal=layout.direction==='horizontal',mainSize=horizontal?innerWidth:innerHeight,fills=children.filter((child)=>(horizontal?child.widthMode:child.heightMode)==='fill'),fixedTotal=children.reduce((sum,child)=>{const current=next[child.id];return sum+(horizontal?current.width:current.height)},0)
  if(fills.length){const nonFill=fixedTotal-fills.reduce((sum,child)=>sum+(horizontal?next[child.id].width:next[child.id].height),0),available=Math.max(1,(mainSize-nonFill-gap*Math.max(0,children.length-1))/fills.length);for(const child of fills)next[child.id]={...next[child.id],...(horizontal?{width:round(available)}:{height:round(available)})}}
  const sized=children.map((child)=>next[child.id]),total=sized.reduce((sum,child)=>sum+(horizontal?child.width:child.height),0),spacing=distributedSpacing(distribution,mainSize,total,sized.length,gap);let cursor=(horizontal?padding.left:padding.top)+spacing.start
  for(const child of sized){const crossSize=horizontal?innerHeight:innerWidth,cross=alignOffset(align,crossSize,horizontal?child.height:child.width),patch:Partial<CanvasNode>=horizontal?{x:round(cursor),y:round(padding.top+cross)}:{x:round(padding.left+cross),y:round(cursor)};if(align==='stretch')horizontal?patch.height=Math.max(1,round(innerHeight)):patch.width=Math.max(1,round(innerWidth));next[child.id]={...child,...patch};cursor+=(horizontal?next[child.id].width:next[child.id].height)+spacing.gap}
  const contentMain=sized.reduce((sum,child)=>sum+(horizontal?next[child.id].width:next[child.id].height),0)+gap*Math.max(0,sized.length-1),contentCross=Math.max(1,...sized.map((child)=>horizontal?next[child.id].height:next[child.id].width));next[frameId]={...frame,...(frame.widthMode==='hug'?{width:round((horizontal?contentMain:contentCross)+padding.left+padding.right)}:{}),...(frame.heightMode==='hug'?{height:round((horizontal?contentCross:contentMain)+padding.top+padding.bottom)}:{})}
  return next
}

function applyGrid(objects:Record<string,CanvasNode>,children:CanvasNode[],frame:CanvasNode,padding:ReturnType<typeof pads>,gap:number,align:LayoutAlignment){const next={...objects},columns=Math.max(1,Math.round(frame.layout?.columns??2)),innerWidth=Math.max(1,frame.width-padding.left-padding.right),cellWidth=Math.max(1,(innerWidth-gap*(columns-1))/columns),rows=Math.ceil(children.length/columns),rowHeights=Array.from({length:rows},(_,row)=>Math.max(1,...children.slice(row*columns,(row+1)*columns).map((child)=>child.height)));let y=padding.top;for(let row=0;row<rows;row++){for(let column=0;column<columns;column++){const child=children[row*columns+column];if(!child)continue;let width=child.width;if(child.widthMode==='fill')width=cellWidth;if(child.widthMode==='percent')width=cellWidth*Math.max(0,child.widthPercent??100)/100;const offset=alignOffset(align,cellWidth,width);next[child.id]={...child,width:round(width),x:round(padding.left+column*(cellWidth+gap)+offset),y:round(y)}}y+=rowHeights[row]+gap}const contentHeight=rowHeights.reduce((sum,value)=>sum+value,0)+gap*Math.max(0,rows-1);next[frame.id]={...frame,...(frame.heightMode==='hug'?{height:round(contentHeight+padding.top+padding.bottom)}:{})};return next}
function distributedSpacing(mode:LayoutDistribution,available:number,total:number,count:number,fallback:number){const free=Math.max(0,available-total);if(count<1)return{start:0,gap:0};if(mode==='between'&&count>1)return{start:0,gap:free/(count-1)};if(mode==='around')return{start:free/count/2,gap:free/count};if(mode==='evenly')return{start:free/(count+1),gap:free/(count+1)};if(mode==='center')return{start:free/2,gap:fallback};if(mode==='end')return{start:free,gap:fallback};return{start:0,gap:fallback}}
function alignOffset(align:LayoutAlignment,available:number,size:number){if(align==='center')return(available-size)/2;if(align==='end')return available-size;return 0}

export function reflowLayoutChain(objects:Record<string,CanvasNode>,order:string[],startIds:string[]):Record<string,CanvasNode>{let next=objects;const frames:string[]=[];for(const id of startIds){const node=next[id];if(node?.layout)frames.push(id);for(const ancestor of ancestorIds(id,next))if(next[ancestor]?.layout)frames.push(ancestor)}for(const frameId of [...new Set(frames)])next=applyAutoLayout(next,order,frameId);return next}

export function applyConstraintsOnResize(objects:Record<string,CanvasNode>,oldFrame:CanvasNode,newFrame:CanvasNode):Record<string,CanvasNode>{if(oldFrame.width===newFrame.width&&oldFrame.height===newFrame.height)return objects;const next={...objects},dx=newFrame.width-oldFrame.width,dy=newFrame.height-oldFrame.height,sx=oldFrame.width?newFrame.width/oldFrame.width:1,sy=oldFrame.height?newFrame.height/oldFrame.height:1;for(const child of Object.values(objects)){if(child.parentId!==oldFrame.id||child.layoutPosition!=='absolute'&&oldFrame.layout)continue;const constraints=child.constraints??{horizontal:'left',vertical:'top'};let{x,y,width,height}=child;if(constraints.horizontal==='right')x+=dx;if(constraints.horizontal==='center')x+=dx/2;if(constraints.horizontal==='stretch')width=Math.max(1,width+dx);if(constraints.horizontal==='scale'){x*=sx;width=Math.max(1,width*sx)}if(constraints.vertical==='bottom')y+=dy;if(constraints.vertical==='center')y+=dy/2;if(constraints.vertical==='stretch')height=Math.max(1,height+dy);if(constraints.vertical==='scale'){y*=sy;height=Math.max(1,height*sy)}next[child.id]={...child,x:round(x),y:round(y),width:round(width),height:round(height)}}return next}
