import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { CanvasNode, EditorMode, EditorSnapshot, EditorStyle, EditorStyleType, EditorVariable, LayoutDirection, NodeType, Point, SidebarTab, Tool, VariableType, ViewportState } from '../types/editor'
import { clamp, rectUnion } from '../lib/geometry'
import { ancestorIds, migrateAbsoluteScene, reparentPatch, worldBounds, worldCenter, worldRotation, worldVectorToParent } from '../editor/scene/sceneGraph'
import { applyAutoLayout, applyConstraintsOnResize, reflowLayoutChain } from '../editor/layout/layoutEngine'

const MAX_HISTORY = 100
const uid = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`
const commonNode = (type: NodeType, x: number, y: number) => ({
  id: uid(type), type, x, y, rotation: 0, opacity: 1,
  fill: '#d9d9d9', fillOpacity: 1, stroke: '#202020', strokeOpacity: 1, strokeWidth: 1, radius: 0,
  visible: true, locked: false, parentId: null,
  shadowEnabled: false, shadowX: 0, shadowY: 4, shadowBlur: 12, shadowColor: '#00000055',
})
const defaultNode = (type: NodeType, x: number, y: number): CanvasNode => {
  const common = commonNode(type, x, y)
  if (type === 'group') return { ...common, name: 'Группа', width: 240, height: 160, fill: 'transparent', stroke: 'transparent', strokeWidth: 0 }
  if (type === 'frame') return { ...common, name: 'Фрейм', width: 520, height: 360, fill: '#f2f2f2', stroke: '#d0d0d0' }
  if (type === 'ellipse') return { ...common, name: 'Эллипс', width: 220, height: 220, radius: 9999 }
  if (type === 'text') return { ...common, name: 'Текст', width: 240, height: 56, fill: 'transparent', stroke: 'transparent', strokeWidth: 0, text: 'Текст', fontFamily: 'Inter, Arial, sans-serif', fontSize: 28, fontWeight: 600, lineHeight: 1.2, letterSpacing: 0, textAlign: 'left', textVerticalAlign: 'top', textDecoration: 'none', textTransform: 'none' }
  if (type === 'sticky') return { ...common, name: 'Заметка', width: 220, height: 180, fill: '#f6e58d', stroke: '#e8d36c', radius: 8, text: 'Новая заметка', fontFamily: 'Inter, Arial, sans-serif', fontSize: 18, fontWeight: 600, lineHeight: 1.35, letterSpacing: 0, textAlign: 'left', textVerticalAlign: 'top', textDecoration: 'none', textTransform: 'none' }
  if (type === 'path') return { ...common, name: 'Контур', width: 1, height: 1, fill: 'transparent', stroke: '#f3f3f3', strokeWidth: 3, path: [], pathStyle: 'pencil', pathClosed: false, strokeCap: 'round', strokeJoin: 'round' }
  if (type === 'image') return { ...common, name: 'Изображение', width: 320, height: 240, fill: 'transparent', stroke: 'transparent', strokeWidth: 0 }
  return { ...common, name: 'Прямоугольник', width: 260, height: 180 }
}

interface EditorState {
  objects: Record<string, CanvasNode>; order: string[]; selectedIds: string[]; tool: Tool; mode: EditorMode
  viewport: ViewportState; past: EditorSnapshot[]; future: EditorSnapshot[]; clipboard: CanvasNode[]
  theme: 'dark' | 'light'; sidebarTab: SidebarTab; motionTime: number; motionDuration: number; variables: EditorVariable[]; styles: EditorStyle[]; previewOpen: boolean
  setTool: (tool: Tool) => void; setMode: (mode: EditorMode) => void; setSidebarTab: (tab: SidebarTab) => void
  setViewport: (patch: Partial<ViewportState>) => void; resetViewport: () => void
  addNode: (type: NodeType, x: number, y: number, patch?: Partial<CanvasNode>) => string
  addPathNode: (points: Point[], style: 'pen' | 'pencil' | 'brush') => string
  updateNode: (id: string, patch: Partial<CanvasNode>, record?: boolean) => void
  updateNodes: (updates: Array<{ id: string; patch: Partial<CanvasNode> }>, record?: boolean) => void
  selectOnly: (id: string) => void; toggleSelection: (id: string) => void; setSelection: (ids: string[]) => void; clearSelection: () => void
  deleteSelected: () => void; duplicateSelected: () => void; copySelected: () => void; paste: () => void
  groupSelected: () => void; ungroupSelected: () => void
  checkpoint: () => void; undo: () => void; redo: () => void
  toggleVisible: (id: string) => void; toggleLocked: (id: string) => void; renameNode: (id: string, name: string) => void; setTheme: (theme: 'dark' | 'light') => void
  moveLayer: (id: string, direction: 1 | -1) => void; reorderLayer: (dragId: string, targetId: string, visualPosition: 'above' | 'below') => void
  setParent: (id: string, parentId: string | null, record?: boolean) => void; getDescendants: (id: string) => string[]
  commitLayout: (ids: string[]) => void
  setMotionTime: (time: number) => void; setMotionDuration: (duration: number) => void; addKeyframe: (id: string, time?: number) => void
  setPreviewOpen: (open: boolean) => void
  addVariable: (name: string, type: VariableType, value: string | number) => void; updateVariable: (id: string, patch: Partial<EditorVariable>) => void; deleteVariable: (id: string) => void
  bindVariable: (nodeId: string, property: 'fill' | 'stroke' | 'opacity' | 'radius' | 'fontSize', variableId: string | null) => void
  createStyleFromSelection: (type: EditorStyleType, name: string) => void; applyStyle: (nodeId: string, styleId: string | null, type?: EditorStyleType) => void; deleteStyle: (id: string) => void
  alignSelected: (axis: 'left' | 'centerX' | 'right' | 'top' | 'centerY' | 'bottom') => void; distributeSelected: (axis: 'x' | 'y') => void
  renameSelectedIntelligently: () => void; cleanupEmptyLayers: () => void; createAutoLayout: (direction?: LayoutDirection) => void
  createComponentFromSelection: () => void; createInstance: (componentId: string, x?: number, y?: number) => void; resetInstanceOverrides: (instanceId: string) => void; detachInstance: (instanceId: string) => void
  replaceDocument: (document: Pick<EditorState, 'objects' | 'order' | 'selectedIds' | 'variables' | 'styles'>) => void
}
const snapshot = (state: Pick<EditorState, 'objects' | 'order' | 'selectedIds' | 'variables' | 'styles'>): EditorSnapshot => ({ objects: structuredClone(state.objects), order: [...state.order], selectedIds: [...state.selectedIds], variables: structuredClone(state.variables), styles: structuredClone(state.styles) })
const pushPast = (state: EditorState): Pick<EditorState, 'past' | 'future'> => ({ past: [...state.past.slice(-(MAX_HISTORY - 1)), snapshot(state)], future: [] })
const topLevelSelection = (ids:string[],objects:Record<string,CanvasNode>) => ids.filter((id)=>!ancestorIds(id,objects).some((parentId)=>ids.includes(parentId)))
const detachedSnapshot = (node:CanvasNode,objects:Record<string,CanvasNode>):CanvasNode => { const center=worldCenter(node.id,objects);return{...structuredClone(node),x:center.x-node.width/2,y:center.y-node.height/2,rotation:worldRotation(node.id,objects),parentId:null} }
const componentMasterFor = (id:string,objects:Record<string,CanvasNode>):string|null => { let current:CanvasNode|undefined=objects[id],guard=0;while(current&&guard++<1000){if(current.componentRole==='component')return current.id;current=current.parentId?objects[current.parentId]:undefined}return null }
const componentTreeIds = (rootId:string,objects:Record<string,CanvasNode>,order:string[]) => { const ids=new Set([rootId]);let changed=true;while(changed){changed=false;for(const id of order){const node=objects[id];if(node?.parentId&&ids.has(node.parentId)&&!ids.has(id)){ids.add(id);changed=true}}}return order.filter((id)=>ids.has(id)) }
const syncableComponentKeys = (patch:Partial<CanvasNode>) => Object.keys(patch).filter((key)=>!['id','parentId','componentRole','mainComponentId','componentSourceId','componentOverrides'].includes(key)) as Array<keyof CanvasNode>
const styleProperties = (node:CanvasNode,type:EditorStyleType):Partial<CanvasNode> => type==='paint'?{fill:node.fill,fillOpacity:node.fillOpacity,stroke:node.stroke,strokeOpacity:node.strokeOpacity,strokeWidth:node.strokeWidth,radius:node.radius}:type==='text'?{fontFamily:node.fontFamily,fontSize:node.fontSize,fontWeight:node.fontWeight,lineHeight:node.lineHeight,letterSpacing:node.letterSpacing,textAlign:node.textAlign,textVerticalAlign:node.textVerticalAlign,textDecoration:node.textDecoration,textTransform:node.textTransform}:{shadowEnabled:node.shadowEnabled,shadowX:node.shadowX,shadowY:node.shadowY,shadowBlur:node.shadowBlur,shadowColor:node.shadowColor,opacity:node.opacity}

export const useEditorStore = create<EditorState>()(persist((set, get) => ({
  objects: {}, order: [], selectedIds: [], tool: 'select', mode: 'design', viewport: { x: 360, y: 220, zoom: 1 }, past: [], future: [], clipboard: [], theme: 'dark', sidebarTab: 'file', motionTime: 0, motionDuration: 2000, variables: [], styles: [], previewOpen: false,
  setTool: (tool) => set({ tool }),
  setMode: (mode) => set({ mode, tool: mode === 'draw' ? 'pencil' : 'select' }),
  setSidebarTab: (sidebarTab) => set({ sidebarTab }),
  setViewport: (patch) => set((state) => ({ viewport: { ...state.viewport, ...patch, zoom: clamp(patch.zoom ?? state.viewport.zoom, 0.1, 4) } })),
  resetViewport: () => set({ viewport: { x: 360, y: 220, zoom: 1 } }),
  addNode: (type, x, y, patch) => { const node = { ...defaultNode(type, x, y), ...patch }; set((state) => ({ ...pushPast(state), objects: { ...state.objects, [node.id]: node }, order: [...state.order, node.id], selectedIds: [node.id] })); return node.id },
  addPathNode: (points, style) => {
    if (points.length < 2) return ''
    const minX = Math.min(...points.map((p) => p.x)), minY = Math.min(...points.map((p) => p.y)), maxX = Math.max(...points.map((p) => p.x)), maxY = Math.max(...points.map((p) => p.y))
    const node = defaultNode('path', minX, minY)
    node.path = points.map((p) => ({ x: p.x - minX, y: p.y - minY })); node.width = Math.max(1, maxX - minX); node.height = Math.max(1, maxY - minY); node.pathStyle = style; node.strokeWidth = style === 'brush' ? 12 : style === 'pen' ? 2 : 4
    set((state) => ({ ...pushPast(state), objects: { ...state.objects, [node.id]: node }, order: [...state.order, node.id], selectedIds: [node.id] })); return node.id
  },
  updateNode: (id, patch, record = true) => set((state) => { const node=state.objects[id];if(!node)return state;const keys=syncableComponentKeys(patch),isInstance=!!node.componentSourceId&&node.componentRole!=='component',overrides=isInstance?Array.from(new Set([...(node.componentOverrides??[]),...keys.map(String)])):node.componentOverrides;const updated={...node,...patch,componentOverrides:overrides};let objects={...state.objects,[id]:updated};const masterId=componentMasterFor(id,state.objects);if(masterId){for(const target of Object.values(objects)){if(target.id===id||target.componentSourceId!==id||target.componentRole==='component')continue;const allowed=keys.filter((key)=>!(target.componentOverrides??[]).includes(String(key)));if(!allowed.length)continue;const propagated:Partial<CanvasNode>={};for(const key of allowed)(propagated as Record<string,unknown>)[key]=patch[key];objects[target.id]={...target,...propagated}}}if(node.type==='frame'&&(node.width!==updated.width||node.height!==updated.height)){objects=applyConstraintsOnResize(objects,node,updated);if(updated.layout)objects=applyAutoLayout(objects,state.order,id)}if(record)objects=reflowLayoutChain(objects,state.order,[id]);return{...(record?pushPast(state):{}),objects} }),
  updateNodes: (updates, record = true) => set((state) => { let objects={...state.objects};const ids:string[]=[];for(const {id,patch} of updates){const node=objects[id];if(!node)continue;const updated={...node,...patch};objects[id]=updated;ids.push(id);if(node.type==='frame'&&(node.width!==updated.width||node.height!==updated.height))objects=applyConstraintsOnResize(objects,node,updated)}if(record)objects=reflowLayoutChain(objects,state.order,ids);return{...(record?pushPast(state):{}),objects} }),
  selectOnly: (id) => set({ selectedIds: [id] }), toggleSelection: (id) => set((state) => ({ selectedIds: state.selectedIds.includes(id) ? state.selectedIds.filter((x) => x !== id) : [...state.selectedIds, id] })), setSelection: (ids) => set({ selectedIds: ids }), clearSelection: () => set({ selectedIds: [] }), checkpoint: () => set((state) => pushPast(state)),
  deleteSelected: () => set((state) => { if (!state.selectedIds.length) return state; const ids = new Set(state.selectedIds);let changed=true;while(changed){changed=false;for(const node of Object.values(state.objects))if(node.parentId&&ids.has(node.parentId)&&!ids.has(node.id)){ids.add(node.id);changed=true}}const objects={...state.objects};ids.forEach((id)=>delete objects[id]);return{...pushPast(state),objects,order:state.order.filter((id)=>!ids.has(id)),selectedIds:[]} }),
  duplicateSelected: () => { get().copySelected(); get().paste() }, copySelected: () => set((state) => { const roots=topLevelSelection(state.selectedIds,state.objects),ids=new Set(roots);let changed=true;while(changed){changed=false;for(const node of Object.values(state.objects))if(node.parentId&&ids.has(node.parentId)&&!ids.has(node.id)){ids.add(node.id);changed=true}}const clipboard=state.order.filter((id)=>ids.has(id)).map((id)=>roots.includes(id)?detachedSnapshot(state.objects[id],state.objects):structuredClone(state.objects[id]));return{clipboard} }),
  paste: () => set((state) => { if (!state.clipboard.length) return state;const idMap=new Map(state.clipboard.map((node)=>[node.id,uid(node.type)])),objects={...state.objects},order=[...state.order],createdRoots:string[]=[];for(const source of state.clipboard){const id=idMap.get(source.id)!;const parentId=source.parentId?idMap.get(source.parentId)??null:null;objects[id]={...structuredClone(source),id,name:parentId?source.name:`${source.name} — копия`,x:source.x+(parentId?0:28),y:source.y+(parentId?0:28),parentId};order.push(id);if(!parentId)createdRoots.push(id)}return{...pushPast(state),objects,order,selectedIds:createdRoots} }),
  groupSelected: () => set((state) => { const roots=topLevelSelection(state.selectedIds,state.objects);if(!roots.length)return state;const nodes=roots.map(id=>state.objects[id]).filter(Boolean),bounds=rectUnion(nodes.map(node=>worldBounds(node.id,state.objects))),group=defaultNode('group',bounds.x,bounds.y),commonParent=nodes.every(node=>node.parentId===nodes[0].parentId)?nodes[0].parentId??null:null;group.width=Math.max(1,bounds.width);group.height=Math.max(1,bounds.height);let objects={...state.objects,[group.id]:group};if(commonParent){const patch=reparentPatch(group.id,commonParent,objects);if(patch)objects[group.id]={...group,...patch}}for(const node of nodes){const patch=reparentPatch(node.id,group.id,objects);if(patch)objects[node.id]={...objects[node.id],...patch}}const maxIndex=Math.max(...roots.map(id=>state.order.indexOf(id))),order=[...state.order];order.splice(maxIndex+1,0,group.id);return{...pushPast(state),objects,order,selectedIds:[group.id]} }),
  ungroupSelected: () => set((state) => { const groups=topLevelSelection(state.selectedIds,state.objects).filter(id=>state.objects[id]?.type==='group');if(!groups.length)return state;let objects={...state.objects},order=[...state.order];const selected:string[]=[];for(const groupId of groups){const group=objects[groupId],children=order.filter(id=>objects[id]?.parentId===groupId);for(const childId of children){const patch=reparentPatch(childId,group.parentId??null,objects);if(patch)objects[childId]={...objects[childId],...patch};selected.push(childId)}delete objects[groupId];order=order.filter(id=>id!==groupId)}return{...pushPast(state),objects,order,selectedIds:selected} }),
  undo: () => set((state) => { if (!state.past.length) return state; const previous = state.past[state.past.length - 1]; return { objects: structuredClone(previous.objects), order: [...previous.order], selectedIds: [...previous.selectedIds], variables: structuredClone(previous.variables), styles: structuredClone(previous.styles??[]), past: state.past.slice(0, -1), future: [snapshot(state), ...state.future].slice(0, MAX_HISTORY) } }),
  redo: () => set((state) => { if (!state.future.length) return state; const next = state.future[0]; return { objects: structuredClone(next.objects), order: [...next.order], selectedIds: [...next.selectedIds], variables: structuredClone(next.variables), styles: structuredClone(next.styles??[]), past: [...state.past, snapshot(state)].slice(-MAX_HISTORY), future: state.future.slice(1) } }),
  toggleVisible: (id) => get().updateNode(id, { visible: !get().objects[id]?.visible }), toggleLocked: (id) => get().updateNode(id, { locked: !get().objects[id]?.locked }), renameNode: (id, name) => get().updateNode(id, { name }), setTheme: (theme) => set({ theme }),
  moveLayer: (id, direction) => set((state) => { const index = state.order.indexOf(id), nextIndex = clamp(index + direction, 0, state.order.length - 1); if (index < 0 || index === nextIndex) return state; const order = [...state.order]; order.splice(index, 1); order.splice(nextIndex, 0, id); return { ...pushPast(state), order } }),
  reorderLayer: (dragId, targetId, visualPosition) => set((state) => { if (dragId === targetId) return state; const order = state.order.filter((id) => id !== dragId), targetIndex = order.indexOf(targetId); if (targetIndex < 0) return state; order.splice(visualPosition === 'above' ? targetIndex + 1 : targetIndex, 0, dragId); return { ...pushPast(state), order } }),
  setParent: (id, parentId, record = true) => set((state) => { const node=state.objects[id],oldParent=node?.parentId??null,patch=reparentPatch(id,parentId,state.objects);if(!patch)return state;let objects={...state.objects,[id]:{...state.objects[id],...patch}};if(record)objects=reflowLayoutChain(objects,state.order,[id,...(oldParent?[oldParent]:[]),...(parentId?[parentId]:[])]);return{...(record?pushPast(state):{}),objects} }),
  getDescendants: (id) => { const { objects } = get(), out: string[] = []; const visit = (parentId: string) => { for (const node of Object.values(objects)) if (node.parentId === parentId) { out.push(node.id); visit(node.id) } }; visit(id); return out },
  commitLayout: (ids) => set((state)=>{let order=[...state.order],objects=state.objects;const parents=new Set(ids.map((id)=>objects[id]?.parentId).filter((id):id is string=>!!id&&!!objects[id]?.layout));for(const parentId of parents){const layout=objects[parentId].layout!,siblings=order.filter((id)=>objects[id]?.parentId===parentId&&objects[id].layoutPosition!=='absolute'),sorted=[...siblings].sort((a,b)=>layout.direction==='horizontal'?objects[a].x-objects[b].x:layout.direction==='vertical'?objects[a].y-objects[b].y:objects[a].y-objects[b].y||objects[a].x-objects[b].x),indices=siblings.map((id)=>order.indexOf(id)),insert=Math.min(...indices);order=order.filter((id)=>!siblings.includes(id));order.splice(insert,0,...sorted);objects=applyAutoLayout(objects,order,parentId)}return{order,objects} }),
  setMotionTime: (time) => set((s) => ({ motionTime: clamp(time, 0, s.motionDuration) })), setMotionDuration: (duration) => set({ motionDuration: clamp(duration, 200, 20000) }),
  addKeyframe: (id, time) => set((state) => { const node = state.objects[id]; if (!node) return state; const t = time ?? state.motionTime; const keyframe = { id: uid('kf'), time: t, x: node.x, y: node.y, width: node.width, height: node.height, rotation: node.rotation, opacity: node.opacity }; const existing = (node.keyframes ?? []).filter((k) => Math.abs(k.time - t) > 1); return { ...pushPast(state), objects: { ...state.objects, [id]: { ...node, keyframes: [...existing, keyframe].sort((a, b) => a.time - b.time) } } } })
  ,setPreviewOpen: (previewOpen) => set({ previewOpen }),
  addVariable: (name, type, value) => set((state) => ({ ...pushPast(state), variables: [...state.variables, { id: uid('var'), name, type, value }] })),
  updateVariable: (id, patch) => set((state) => { const variables=state.variables.map((item)=>item.id===id?{...item,...patch}:item),variable=variables.find((item)=>item.id===id);if(!variable)return state;const objects={...state.objects};for(const node of Object.values(objects)){const entries=Object.entries(node.variableBindings??{}).filter(([,variableId])=>variableId===id);if(!entries.length)continue;const next={...node};for(const [property] of entries)(next as unknown as Record<string,unknown>)[property]=variable.value;objects[node.id]=next}return{...pushPast(state),variables,objects} }),
  deleteVariable: (id) => set((state) => { const objects={...state.objects};for(const node of Object.values(objects)){if(!Object.values(node.variableBindings??{}).includes(id))continue;objects[node.id]={...node,variableBindings:Object.fromEntries(Object.entries(node.variableBindings??{}).filter(([,variableId])=>variableId!==id))}}return{...pushPast(state),variables:state.variables.filter((item)=>item.id!==id),objects} }),
  bindVariable: (nodeId,property,variableId) => set((state) => { const node=state.objects[nodeId];if(!node)return state;const bindings={...(node.variableBindings??{})};if(!variableId)delete bindings[property];else bindings[property]=variableId;const variable=state.variables.find((item)=>item.id===variableId),patch:Partial<CanvasNode>={variableBindings:bindings};if(variable)(patch as unknown as Record<string,unknown>)[property]=variable.value;return{...pushPast(state),objects:{...state.objects,[nodeId]:{...node,...patch}}} }),
  createStyleFromSelection: (type,name) => set((state) => { const node=state.objects[state.selectedIds[0]];if(!node||!name.trim())return state;const style:EditorStyle={id:uid('style'),name:name.trim(),type,properties:styleProperties(node,type)};const key=type==='paint'?'paintStyleId':type==='text'?'textStyleId':'effectStyleId';return{...pushPast(state),styles:[...state.styles,style],objects:{...state.objects,[node.id]:{...node,[key]:style.id}}} }),
  applyStyle: (nodeId,styleId,type) => set((state) => { const node=state.objects[nodeId];if(!node)return state;if(!styleId){const key=type==='text'?'textStyleId':type==='effect'?'effectStyleId':'paintStyleId';return{...pushPast(state),objects:{...state.objects,[nodeId]:{...node,[key]:undefined}}}}const style=state.styles.find((item)=>item.id===styleId);if(!style)return state;const key=style.type==='paint'?'paintStyleId':style.type==='text'?'textStyleId':'effectStyleId';return{...pushPast(state),objects:{...state.objects,[nodeId]:{...node,...style.properties,[key]:style.id}}} }),
  deleteStyle: (id) => set((state) => { const objects={...state.objects};for(const node of Object.values(objects)){if(node.paintStyleId===id)objects[node.id]={...node,paintStyleId:undefined};else if(node.textStyleId===id)objects[node.id]={...node,textStyleId:undefined};else if(node.effectStyleId===id)objects[node.id]={...node,effectStyleId:undefined}}return{...pushPast(state),styles:state.styles.filter((item)=>item.id!==id),objects} }),
  alignSelected: (axis) => set((state) => { const ids=topLevelSelection(state.selectedIds,state.objects),nodes=ids.map((id)=>state.objects[id]).filter(Boolean);if(nodes.length<2)return state;const boxes=new Map(nodes.map((node)=>[node.id,worldBounds(node.id,state.objects)])),bounds=rectUnion([...boxes.values()]),objects={...state.objects};for(const node of nodes){const box=boxes.get(node.id)!;let dx=0,dy=0;if(axis==='left')dx=bounds.x-box.x;if(axis==='centerX')dx=bounds.x+bounds.width/2-(box.x+box.width/2);if(axis==='right')dx=bounds.x+bounds.width-(box.x+box.width);if(axis==='top')dy=bounds.y-box.y;if(axis==='centerY')dy=bounds.y+bounds.height/2-(box.y+box.height/2);if(axis==='bottom')dy=bounds.y+bounds.height-(box.y+box.height);const local=worldVectorToParent({x:dx,y:dy},node.parentId,state.objects);objects[node.id]={...node,x:node.x+local.x,y:node.y+local.y}}return{...pushPast(state),objects} }),
  distributeSelected: (axis) => set((state) => { const ids=topLevelSelection(state.selectedIds,state.objects),nodes=ids.map((id)=>state.objects[id]).filter(Boolean);if(nodes.length<3)return state;const boxes=new Map(nodes.map((node)=>[node.id,worldBounds(node.id,state.objects)])),sorted=[...nodes].sort((a,b)=>axis==='x'?boxes.get(a.id)!.x-boxes.get(b.id)!.x:boxes.get(a.id)!.y-boxes.get(b.id)!.y),bounds=rectUnion([...boxes.values()]),total=sorted.reduce((sum,node)=>sum+(axis==='x'?boxes.get(node.id)!.width:boxes.get(node.id)!.height),0),gap=((axis==='x'?bounds.width:bounds.height)-total)/(sorted.length-1),objects={...state.objects};let cursor=axis==='x'?bounds.x:bounds.y;for(const node of sorted){const box=boxes.get(node.id)!,delta=axis==='x'?{x:cursor-box.x,y:0}:{x:0,y:cursor-box.y},local=worldVectorToParent(delta,node.parentId,state.objects);objects[node.id]={...node,x:node.x+local.x,y:node.y+local.y};cursor+=(axis==='x'?box.width:box.height)+gap}return{...pushPast(state),objects} }),
  renameSelectedIntelligently: () => set((state) => { if (!state.selectedIds.length) return state; const counters: Record<string, number> = {}; const labels: Record<NodeType, string> = { frame: 'Фрейм', group:'Группа', rectangle: 'Прямоугольник', ellipse: 'Эллипс', text: 'Текст', sticky: 'Заметка', path: 'Контур', image: 'Изображение' }; const objects = { ...state.objects }; for (const id of state.selectedIds) { const node = objects[id]; if (!node) continue; counters[node.type] = (counters[node.type] ?? 0) + 1; objects[id] = { ...node, name: `${labels[node.type]} ${counters[node.type]}` } } return { ...pushPast(state), objects } }),
  cleanupEmptyLayers: () => set((state) => { const removable = new Set(Object.values(state.objects).filter((node) => (node.type === 'text' || node.type === 'sticky') && !(node.text ?? '').trim()).map((node) => node.id)); if (!removable.size) return state; const objects = { ...state.objects }; removable.forEach((id) => delete objects[id]); return { ...pushPast(state), objects, order: state.order.filter((id) => !removable.has(id)), selectedIds: state.selectedIds.filter((id) => !removable.has(id)) } }),
  createAutoLayout: (direction = 'horizontal') => set((state) => { const roots=topLevelSelection(state.selectedIds,state.objects),selected=roots.map((id)=>state.objects[id]).filter(Boolean);if(!selected.length)return state;let objects={...state.objects},frame:CanvasNode|undefined=selected.length===1&&selected[0].type==='frame'?selected[0]:undefined,order=state.order;if(!frame){const bounds=rectUnion(selected.map((node)=>worldBounds(node.id,state.objects)));frame=defaultNode('frame',bounds.x-24,bounds.y-24);frame.name=direction==='grid'?'Сеточный макет':'Автомакет';objects[frame.id]=frame;order=[...order,frame.id];for(const node of selected){const patch=reparentPatch(node.id,frame.id,objects);if(patch)objects[node.id]={...node,...patch}}}objects[frame.id]={...objects[frame.id],layout:{direction,gap:16,padding:24,distribution:'start',align:'start',columns:2}};objects=applyAutoLayout(objects,order,frame.id);return{...pushPast(state),objects,order,selectedIds:[frame.id]} }),
  createComponentFromSelection: () => set((state) => { const roots=topLevelSelection(state.selectedIds,state.objects);if(roots.length!==1)return state;const root=state.objects[roots[0]];if(!root||root.componentRole==='instance')return state;const objects={...state.objects,[root.id]:{...root,componentRole:'component' as const,componentSourceId:root.id,name:root.name.startsWith('Компонент')?root.name:`Компонент / ${root.name}`}};for(const id of componentTreeIds(root.id,objects,state.order)){if(id===root.id)continue;objects[id]={...objects[id],componentSourceId:id}}return{...pushPast(state),objects,selectedIds:[root.id]} }),
  createInstance: (componentId,x,y) => set((state) => { const master=state.objects[componentId];if(!master||master.componentRole!=='component')return state;const sourceIds=componentTreeIds(componentId,state.objects,state.order),idMap=new Map(sourceIds.map((id)=>[id,uid(state.objects[id].type)])),objects={...state.objects},order=[...state.order];for(const sourceId of sourceIds){const source=state.objects[sourceId],id=idMap.get(sourceId)!,isRoot=sourceId===componentId,parentId=isRoot?null:idMap.get(source.parentId??'')??null;objects[id]={...structuredClone(source),id,parentId,componentRole:isRoot?'instance':undefined,mainComponentId:isRoot?componentId:undefined,componentSourceId:sourceId,componentOverrides:isRoot?['x','y','rotation']:[],name:isRoot?`${master.name} / экземпляр`:source.name,x:isRoot?(x??source.x+48):source.x,y:isRoot?(y??source.y+48):source.y};order.push(id)}const rootId=idMap.get(componentId)!;return{...pushPast(state),objects,order,selectedIds:[rootId]} }),
  resetInstanceOverrides: (instanceId) => set((state) => { const instance=state.objects[instanceId],masterId=instance?.mainComponentId;if(!instance||instance.componentRole!=='instance'||!masterId||!state.objects[masterId])return state;const ids=componentTreeIds(instanceId,state.objects,state.order),objects={...state.objects};for(const id of ids){const node=objects[id],source=state.objects[node.componentSourceId??''];if(!source)continue;const keep=id===instanceId?{x:node.x,y:node.y,rotation:node.rotation,parentId:node.parentId,name:node.name}:{parentId:node.parentId};objects[id]={...structuredClone(source),...keep,id,componentRole:id===instanceId?'instance':undefined,mainComponentId:id===instanceId?masterId:undefined,componentSourceId:source.id,componentOverrides:id===instanceId?['x','y','rotation']:[]}}return{...pushPast(state),objects} }),
  detachInstance: (instanceId) => set((state) => { const instance=state.objects[instanceId];if(!instance||instance.componentRole!=='instance')return state;const objects={...state.objects};for(const id of componentTreeIds(instanceId,state.objects,state.order)){const node=objects[id];objects[id]={...node,componentRole:undefined,mainComponentId:undefined,componentSourceId:undefined,componentOverrides:undefined}}objects[instanceId]={...objects[instanceId],name:objects[instanceId].name.replace(/\s*\/\s*экземпляр$/i,'')};return{...pushPast(state),objects} }),
  replaceDocument: (document) => set((state) => ({ ...pushPast(state), objects: structuredClone(document.objects), order: [...document.order], selectedIds: [...document.selectedIds], variables: structuredClone(document.variables ?? []), styles: structuredClone(document.styles??[]) }))
}), { name: 'nexus-maker-project-v010', version:3, migrate:(persisted,version)=>{const state=persisted as EditorState;let next=state;if(version<2&&state.objects)next={...next,objects:migrateAbsoluteScene(state.objects)};if(version<3)next={...next,styles:state.styles??[]};return next}, partialize: (s) => ({ objects:s.objects, order:s.order, selectedIds:s.selectedIds, viewport:s.viewport, theme:s.theme, sidebarTab:s.sidebarTab, mode:s.mode, motionDuration:s.motionDuration, variables:s.variables,styles:s.styles }) }))
