SMART_PRESETS = [
    {
        "id": "fps_boost",
        "title": "FPS Boost",
        "emoji": "⚡",
        "subtitle": "Для слабых и средних ПК",
        "description": "Оптимизирует Minecraft, повышает FPS и снижает нагрузку на память.",
        "loader": "fabric",
        "recommended_ram": 4096,
        "tags": ["FPS", "Оптимизация", "Слабый ПК"],
        "mods": [
            {
                "slug": "sodium",
                "name": "Sodium",
                "reason": "Главный мод для повышения FPS.",
                "required": True,
            },
            {
                "slug": "lithium",
                "name": "Lithium",
                "reason": "Оптимизирует игровую логику.",
                "required": False,
            },
            {
                "slug": "ferrite-core",
                "name": "FerriteCore",
                "reason": "Снижает потребление оперативной памяти.",
                "required": False,
            },
            {
                "slug": "modernfix",
                "name": "ModernFix",
                "reason": "Исправляет утечки памяти и ускоряет загрузку.",
                "required": False,
            },
            {
                "slug": "modmenu",
                "name": "Mod Menu",
                "reason": "Добавляет удобное меню модов.",
                "required": False,
            },
        ],
    },
    {
        "id": "beautiful",
        "title": "Beautiful Minecraft",
        "emoji": "🌄",
        "subtitle": "Графика, шейдеры и красивый визуал",
        "description": "Сборка для красивого Minecraft с поддержкой шейдеров и визуальных улучшений.",
        "loader": "fabric",
        "recommended_ram": 6144,
        "tags": ["Графика", "Шейдеры", "Красота"],
        "mods": [
            {
                "slug": "sodium",
                "name": "Sodium",
                "reason": "Нужен для высокой производительности.",
                "required": True,
            },
            {
                "slug": "iris",
                "name": "Iris Shaders",
                "reason": "Добавляет поддержку шейдеров.",
                "required": True,
            },
            {
                "slug": "continuity",
                "name": "Continuity",
                "reason": "Улучшает соединённые текстуры.",
                "required": False,
            },
            {
                "slug": "entity-texture-features",
                "name": "Entity Texture Features",
                "reason": "Улучшает поддержку текстур сущностей.",
                "required": False,
            },
            {
                "slug": "modmenu",
                "name": "Mod Menu",
                "reason": "Удобное управление модами.",
                "required": False,
            },
        ],
    },
    {
        "id": "vanilla_plus",
        "title": "Vanilla+",
        "emoji": "🧱",
        "subtitle": "Minecraft без перегруза",
        "description": "Аккуратная сборка, которая сохраняет ванильный стиль, но делает игру удобнее.",
        "loader": "fabric",
        "recommended_ram": 4096,
        "tags": ["Vanilla+", "Удобство", "Минимум лишнего"],
        "mods": [
            {
                "slug": "modmenu",
                "name": "Mod Menu",
                "reason": "Удобное меню установленных модов.",
                "required": True,
            },
            {
                "slug": "appleskin",
                "name": "AppleSkin",
                "reason": "Показывает насыщение и полезную информацию о еде.",
                "required": False,
            },
            {
                "slug": "jade",
                "name": "Jade",
                "reason": "Показывает информацию о блоках и мобах.",
                "required": False,
            },
            {
                "slug": "xaeros-minimap",
                "name": "Xaero's Minimap",
                "reason": "Добавляет удобную миникарту.",
                "required": False,
            },
        ],
    },
    {
        "id": "survival",
        "title": "Survival Adventure",
        "emoji": "⚔",
        "subtitle": "Выживание, исследование и приключения",
        "description": "Сборка для более интересного выживания, карты, информации и приключений.",
        "loader": "fabric",
        "recommended_ram": 6144,
        "tags": ["Выживание", "Карта", "Приключения"],
        "mods": [
            {
                "slug": "xaeros-minimap",
                "name": "Xaero's Minimap",
                "reason": "Миникарта для исследования мира.",
                "required": False,
            },
            {
                "slug": "xaeros-world-map",
                "name": "Xaero's World Map",
                "reason": "Полноценная карта мира.",
                "required": False,
            },
            {
                "slug": "jade",
                "name": "Jade",
                "reason": "Показывает информацию о блоках, мобах и предметах.",
                "required": False,
            },
            {
                "slug": "appleskin",
                "name": "AppleSkin",
                "reason": "Улучшает отображение еды и насыщения.",
                "required": False,
            },
        ],
    },
]