import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { PointerEvent as ReactPointerEvent, ReactNode, WheelEvent as ReactWheelEvent } from 'react'
import { useEditorStore } from '../store/editorStore'
import { calculateCreationRect, contains, horizontalOverlap, intersects, normalizeRect, rectUnion, resizeRect, verticalOverlap, type Point, type Rect } from '../lib/geometry'
import { clientToCanvas, clientToWorld as convertClientToWorld, zoomAtScreenPoint } from '../editor/viewport/coordinates'
import { importImageFile } from '../editor/import/importImage'
import { ancestorIds, invert, transformPoint, worldBounds, worldCenter, worldMatrix, worldPointToParent, worldVectorToParent } from '../editor/scene/sceneGraph'
import type { CanvasNode, NodeType } from '../types/editor'
import { CanvasObject, type RadiusHandle, type ResizeHandle } from './CanvasObject'

interface MoveI { kind:'move'; start:Point; positions:Record<string,Point>; directIds:string[] }
interface ResizeI { kind:'resize'; startInParent:Point; node:CanvasNode; handle:ResizeHandle }
interface RadiusI { kind:'radius'; node:CanvasNode; handle:RadiusHandle }
interface RotateI { kind:'rotate'; node:CanvasNode; center:Point; startAngle:number }
interface PathPointI { kind:'path-point'; node:CanvasNode; index:number }
interface CreateI { kind:'create'; start:Point; id:string; type:NodeType }
interface PanI { kind:'pan'; startClient:Point; startViewport:Point }
type Interaction=MoveI|ResizeI|RadiusI|RotateI|PathPointI|CreateI|PanI|null
interface Guide { axis:'x'|'y'; position:number; start:number; end:number }
interface Measure { axis:'x'|'y'; start:number; end:number; cross:number; value:number }
interface Marquee { screenStart:Point; screenEnd:Point; worldStart:Point; worldEnd:Point }
interface DrawStroke { style:'pen'|'pencil'|'brush'; points:Point[] }

export function CanvasViewport(){
 const ref=useRef<HTMLDivElement>(null), marqueeRef=useRef<Marquee|null>(null)
 const objects=useEditorStore(s=>s.objects), order=useEditorStore(s=>s.order), selectedIds=useEditorStore(s=>s.selectedIds), tool=useEditorStore(s=>s.tool), mode=useEditorStore(s=>s.mode), motionTime=useEditorStore(s=>s.motionTime), viewport=useEditorStore(s=>s.viewport)
 const setViewport=useEditorStore(s=>s.setViewport), setTool=useEditorStore(s=>s.setTool), addNode=useEditorStore(s=>s.addNode), addPathNode=useEditorStore(s=>s.addPathNode), updateNode=useEditorStore(s=>s.updateNode), updateNodes=useEditorStore(s=>s.updateNodes), setSelection=useEditorStore(s=>s.setSelection), selectOnly=useEditorStore(s=>s.selectOnly), toggleSelection=useEditorStore(s=>s.toggleSelection), clearSelection=useEditorStore(s=>s.clearSelection), checkpoint=useEditorStore(s=>s.checkpoint), commitLayout=useEditorStore(s=>s.commitLayout)
 const [interaction,setInteraction]=useState<Interaction>(null), [marquee,setMarquee]=useState<Marquee|null>(null), [stroke,setStroke]=useState<DrawStroke|null>(null), [spaceDown,setSpaceDown]=useState(false), [altDown,setAltDown]=useState(false), [guides,setGuides]=useState<Guide[]>([]), [contextMenu,setContextMenu]=useState<{x:number;y:number;world:Point;nodeId:string|null}|null>(null)
 const clientToLocal=useCallback((x:number,y:number)=>{const r=ref.current?.getBoundingClientRect();return r?clientToCanvas({x,y},r):{x:0,y:0}},[])
 const clientToWorld=useCallback((x:number,y:number)=>{const r=ref.current?.getBoundingClientRect();return r?convertClientToWorld({x,y},r,viewport):{x:0,y:0}},[viewport])
 useEffect(()=>{const kd=(e:KeyboardEvent)=>{if(e.code==='Space'&&!isInput(e.target)){e.preventDefault();setSpaceDown(true)}if(e.key==='Alt')setAltDown(true)};const ku=(e:KeyboardEvent)=>{if(e.code==='Space')setSpaceDown(false);if(e.key==='Alt')setAltDown(false)};window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);return()=>{window.removeEventListener('keydown',kd);window.removeEventListener('keyup',ku)}},[])
 useEffect(()=>{if(!interaction)return;const move=(e:PointerEvent)=>{
   if(interaction.kind==='pan'){setViewport({x:interaction.startViewport.x+e.clientX-interaction.startClient.x,y:interaction.startViewport.y+e.clientY-interaction.startClient.y});return}
   const w=clientToWorld(e.clientX,e.clientY)
   if(interaction.kind==='rotate'){const angle=Math.atan2(w.y-interaction.center.y,w.x-interaction.center.x)*180/Math.PI-interaction.startAngle+interaction.node.rotation;updateNode(interaction.node.id,{rotation:round(e.shiftKey?Math.round(angle/15)*15:angle)},false);return}
   if(interaction.kind==='path-point'){const local=transformPoint(invert(worldMatrix(interaction.node.id,objects)),w),path=[...(objects[interaction.node.id]?.path??interaction.node.path??[])];if(!path[interaction.index])return;path[interaction.index]={x:round(local.x),y:round(local.y)};updateNode(interaction.node.id,{path},false);return}
   if(interaction.kind==='radius'){const n=interaction.node,local=transformPoint(invert(worldMatrix(n.id,objects)),w);let r=0;if(interaction.handle==='nw')r=Math.max(local.x,local.y);if(interaction.handle==='ne')r=Math.max(n.width-local.x,local.y);if(interaction.handle==='se')r=Math.max(n.width-local.x,n.height-local.y);if(interaction.handle==='sw')r=Math.max(local.x,n.height-local.y);updateNode(n.id,{radius:Math.round(Math.max(0,Math.min(Math.min(n.width,n.height)/2,r)))},false);return}
   if(interaction.kind==='create'){const rect=calculateCreationRect(interaction.start,w,e.shiftKey,e.altKey);updateNode(interaction.id,{...rect,width:Math.max(1,rect.width),height:Math.max(1,rect.height)},false);return}
   if(interaction.kind==='move'){let dx=w.x-interaction.start.x,dy=w.y-interaction.start.y;const initialBounds=rectUnion(Object.keys(interaction.positions).map((id)=>worldBounds(id,objects))),bounds={...initialBounds,x:initialBounds.x+dx,y:initialBounds.y+dy},ignored=new Set<string>();for(const id of Object.keys(interaction.positions)){ignored.add(id);for(const childId of Object.keys(objects))if(ancestorIds(childId,objects).includes(id))ignored.add(childId)}const targets=Object.values(objects).filter((n)=>n.visible&&!ignored.has(n.id)).map((n)=>worldBounds(n.id,objects)),snap=calculateSnap(bounds,targets,7/viewport.zoom);dx+=snap.dx;dy+=snap.dy;setGuides(snap.guides);updateNodes(Object.entries(interaction.positions).map(([id,p])=>{const node=objects[id],delta=worldVectorToParent({x:dx,y:dy},node.parentId,objects);return{id,patch:{x:round(p.x+delta.x),y:round(p.y+delta.y)}}}),false);return}
   setGuides([]);const {node,handle,startInParent}=interaction,currentInParent=worldPointToParent(w,node.parentId,objects),rect=resizeRect({x:node.x,y:node.y,width:node.width,height:node.height},handle,{x:currentInParent.x-startInParent.x,y:currentInParent.y-startInParent.y});updateNode(node.id,rect,false)
 };const up=()=>{if(interaction.kind==='move'){assignParents(interaction.directIds);commitLayout(interaction.directIds)}if(interaction.kind==='create'){const n=useEditorStore.getState().objects[interaction.id];if(n&&n.width<5&&n.height<5)updateNode(n.id,{width:interaction.type==='ellipse'?160:220,height:interaction.type==='ellipse'?160:140},false);assignParents([interaction.id]);commitLayout([interaction.id]);setTool('select')}setGuides([]);setInteraction(null)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[interaction,clientToWorld,objects,setViewport,updateNode,updateNodes,viewport.zoom,commitLayout])
 useEffect(()=>{if(!marquee)return;const move=(e:PointerEvent)=>{const m=marqueeRef.current;if(!m)return;const next={...m,screenEnd:clientToLocal(e.clientX,e.clientY),worldEnd:clientToWorld(e.clientX,e.clientY)};marqueeRef.current=next;setMarquee(next)};const up=(e:PointerEvent)=>{const m=marqueeRef.current;if(m){const wr=normalizeRect(m.worldStart,m.worldEnd);const hits=order.filter(id=>{const n=objects[id];return !!n&&n.visible&&!n.locked&&intersects(wr,worldBounds(id,objects))});setSelection(e.shiftKey?Array.from(new Set([...useEditorStore.getState().selectedIds,...hits])):hits)}marqueeRef.current=null;setMarquee(null)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[marquee,clientToLocal,clientToWorld,objects,order,setSelection])
 useEffect(()=>{if(!stroke)return;const move=(e:PointerEvent)=>setStroke(s=>s?{...s,points:[...s.points,clientToWorld(e.clientX,e.clientY)]}:null);const up=()=>{const s=stroke;if(s.points.length>1)addPathNode(s.points,s.style);setStroke(null)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[stroke,clientToWorld,addPathNode])
 const assignParents=(ids:string[])=>{const s=useEditorStore.getState();for(const id of ids){const n=s.objects[id];if(!n)continue;const desc=new Set(s.getDescendants(id)),bounds=worldBounds(id,s.objects),frames=s.order.map(fid=>s.objects[fid]).filter((c):c is CanvasNode=>!!c&&c.type==='frame'&&c.id!==id&&!desc.has(c.id)&&contains(worldBounds(c.id,s.objects),bounds,1)).sort((a,b)=>{const ar=worldBounds(a.id,s.objects),br=worldBounds(b.id,s.objects);return ar.width*ar.height-br.width*br.height});const target=frames[0]?.id??null;if(target!==(n.parentId??null))s.setParent(id,target,false)}}
 const onWheel=(e:ReactWheelEvent)=>{e.preventDefault();const r=ref.current?.getBoundingClientRect();if(!r)return;const next=Math.max(.1,Math.min(4,viewport.zoom*Math.exp(-e.deltaY*.0014))),screen=clientToCanvas({x:e.clientX,y:e.clientY},r);setViewport(zoomAtScreenPoint(viewport,screen,next))}
 const onCanvasDown=(e:ReactPointerEvent<HTMLDivElement>)=>{setContextMenu(null);if(e.button===1||(e.button===0&&spaceDown)){e.preventDefault();setInteraction({kind:'pan',startClient:{x:e.clientX,y:e.clientY},startViewport:{x:viewport.x,y:viewport.y}});return}if(e.button!==0)return;const world=clientToWorld(e.clientX,e.clientY)
   if(mode==='draw'&&(tool==='pen'||tool==='pencil'||tool==='brush')){clearSelection();setStroke({style:tool,points:[world]});return}
   if(tool!=='select'){const type=tool==='frame'||tool==='rectangle'||tool==='ellipse'||tool==='text'||tool==='sticky'?tool:null;if(type){if(type==='text'||type==='sticky'){addNode(type,world.x,world.y);setTool('select')}else{const id=addNode(type,world.x,world.y,{width:1,height:1});setInteraction({kind:'create',start:world,id,type})}return}}
   clearSelection();const m={screenStart:clientToLocal(e.clientX,e.clientY),screenEnd:clientToLocal(e.clientX,e.clientY),worldStart:world,worldEnd:world};marqueeRef.current=m;setMarquee(m)
 }
 const onObjectDown=(node:CanvasNode,e:ReactPointerEvent<HTMLDivElement>)=>{if(e.button!==0||node.locked||spaceDown||tool!=='select')return;e.stopPropagation();if(e.shiftKey){toggleSelection(node.id);return}const current=useEditorStore.getState().selectedIds;if(!current.includes(node.id))selectOnly(node.id);if(mode==='dev')return;const raw=current.includes(node.id)?current:[node.id],direct=raw.filter((id)=>!ancestorIds(id,objects).some((parentId)=>raw.includes(parentId))),positions:Record<string,Point>={};direct.forEach(id=>{const n=objects[id];if(n&&!n.locked)positions[id]={x:n.x,y:n.y}});checkpoint();setInteraction({kind:'move',start:clientToWorld(e.clientX,e.clientY),positions,directIds:direct})}
 const onResize=(n:CanvasNode,h:ResizeHandle,e:ReactPointerEvent<HTMLDivElement>)=>{checkpoint();const world=clientToWorld(e.clientX,e.clientY);setInteraction({kind:'resize',startInParent:worldPointToParent(world,n.parentId,objects),node:structuredClone(n),handle:h})}
 const onRadius=(n:CanvasNode,h:RadiusHandle,_e:ReactPointerEvent<HTMLDivElement>)=>{checkpoint();setInteraction({kind:'radius',node:structuredClone(n),handle:h})}
 const onRotate=(n:CanvasNode,e:ReactPointerEvent<HTMLDivElement>)=>{const start=clientToWorld(e.clientX,e.clientY),center=worldCenter(n.id,objects);checkpoint();setInteraction({kind:'rotate',node:structuredClone(n),center,startAngle:Math.atan2(start.y-center.y,start.x-center.x)*180/Math.PI})}
 const onPathPoint=(n:CanvasNode,index:number,_e:ReactPointerEvent<SVGCircleElement>)=>{checkpoint();setInteraction({kind:'path-point',node:structuredClone(n),index})}
 const measurements=useMemo(()=>{if(!altDown||selectedIds.length!==1)return[];const s=objects[selectedIds[0]];if(!s)return[];const sr=worldBounds(s.id,objects),siblings=Object.values(objects).filter(n=>n.id!==s.id&&n.visible&&n.parentId===s.parentId).map((n)=>worldBounds(n.id,objects)),nearest=nearestMeasurements(sr,siblings);let p=s.parentId?objects[s.parentId]:undefined;if(!p)p=Object.values(objects).filter(n=>n.type==='frame'&&n.id!==s.id&&contains(worldBounds(n.id,objects),sr,0)).sort((a,b)=>{const ar=worldBounds(a.id,objects),br=worldBounds(b.id,objects);return ar.width*ar.height-br.width*br.height})[0];return p?[...nearest,...parentMeasurements(sr,worldBounds(p.id,objects))]:nearest},[altDown,selectedIds,objects])
 const marqueeStyle=marquee?normalizeRect(marquee.screenStart,marquee.screenEnd):undefined
 const childrenByParent=useMemo(()=>{const map=new Map<string,string[]>();for(const id of order){const parentId=objects[id]?.parentId;if(!parentId||!objects[parentId])continue;const list=map.get(parentId)??[];list.push(id);map.set(parentId,list)}return map},[order,objects])
 const renderNode=(id:string,visited=new Set<string>()):ReactNode=>{if(visited.has(id))return null;const source=objects[id];if(!source)return null;const nextVisited=new Set(visited).add(id),node=mode==='motion'?nodeAtTime(source,motionTime):source;return <CanvasObject key={id} node={node} selected={selectedIds.includes(id)} multiSelected={selectedIds.length>1} onPointerDown={onObjectDown} onResizeStart={onResize} onRadiusStart={onRadius} onRotateStart={onRotate} onTextCommit={(target,text)=>{if(text!==target.text)updateNode(target.id,{text})}} onPathPointStart={onPathPoint}>{(childrenByParent.get(id)??[]).map((childId)=>renderNode(childId,nextVisited))}</CanvasObject>}
 const roots=order.filter((id)=>objects[id]&&(!objects[id].parentId||!objects[objects[id].parentId!]))
 return <main ref={ref} className={`canvas-viewport ${spaceDown?'panning-ready':''}`} onWheel={onWheel} onPointerDown={onCanvasDown} onDragOver={e=>{if(Array.from(e.dataTransfer.types).includes('Files'))e.preventDefault()}} onDrop={async e=>{e.preventDefault();const file=Array.from(e.dataTransfer.files).find(item=>/^image\/(png|jpeg|webp|svg\+xml)$/.test(item.type));if(file)await importImageFile(file,clientToWorld(e.clientX,e.clientY),addNode)}} onContextMenu={e=>{e.preventDefault();const target=(e.target as HTMLElement).closest<HTMLElement>('[data-node-id]');const nodeId=target?.dataset.nodeId??null;if(nodeId&&!selectedIds.includes(nodeId))selectOnly(nodeId);setContextMenu({...clientToLocal(e.clientX,e.clientY),world:clientToWorld(e.clientX,e.clientY),nodeId})}}>
   <div className="canvas-world" style={{transform:`translate(${viewport.x}px,${viewport.y}px) scale(${viewport.zoom})`}}>{roots.map((id)=>renderNode(id))}{guides.map((g,i)=><GuideLine key={i} guide={g} zoom={viewport.zoom}/>)}{measurements.map((m,i)=><MeasureLine key={i} measure={m} zoom={viewport.zoom}/>)}{stroke&&<StrokePreview stroke={stroke}/>}</div>
   {marquee&&<div className="marquee marquee-screen" style={marqueeStyle}/>}<div className="canvas-coordinates">{Math.round(viewport.zoom*100)}% · x {Math.round(-viewport.x/viewport.zoom)} · y {Math.round(-viewport.y/viewport.zoom)}</div>
   {contextMenu&&<CanvasContextMenu point={contextMenu} close={()=>setContextMenu(null)}/>} 
 </main>
}

function CanvasContextMenu({point,close}:{point:{x:number;y:number;world:Point;nodeId:string|null};close:()=>void}){const action=(run:()=>void)=>()=>{run();close()};const state=useEditorStore.getState(),isGroup=point.nodeId&&state.objects[point.nodeId]?.type==='group';return <div className="canvas-context-menu" style={{left:point.x,top:point.y}} onPointerDown={e=>e.stopPropagation()}>{point.nodeId?<><button onClick={action(state.duplicateSelected)}>Дублировать <kbd>Ctrl+D</kbd></button><button onClick={action(isGroup?state.ungroupSelected:state.groupSelected)}>{isGroup?'Разгруппировать':'Сгруппировать'} <kbd>{isGroup?'Ctrl+Shift+G':'Ctrl+G'}</kbd></button><button onClick={action(()=>state.toggleVisible(point.nodeId!))}>Скрыть / показать</button><button onClick={action(()=>state.toggleLocked(point.nodeId!))}>Заблокировать / разблокировать</button><hr/><button onClick={action(()=>state.moveLayer(point.nodeId!,1))}>Поднять выше <kbd>]</kbd></button><button onClick={action(()=>state.moveLayer(point.nodeId!,-1))}>Опустить ниже <kbd>[</kbd></button><hr/><button className="danger" onClick={action(state.deleteSelected)}>Удалить <kbd>Del</kbd></button></>:<><button onClick={action(state.paste)}>Вставить <kbd>Ctrl+V</kbd></button><button onClick={action(()=>state.addNode('frame',point.world.x,point.world.y))}>Создать фрейм</button><button onClick={action(()=>state.addNode('text',point.world.x,point.world.y))}>Создать текст</button><button onClick={action(()=>state.addNode('sticky',point.world.x,point.world.y))}>Создать заметку</button></>}</div>}

function StrokePreview({stroke}:{stroke:DrawStroke}){if(stroke.points.length<2)return null;const minX=Math.min(...stroke.points.map(p=>p.x)),minY=Math.min(...stroke.points.map(p=>p.y)),maxX=Math.max(...stroke.points.map(p=>p.x)),maxY=Math.max(...stroke.points.map(p=>p.y)),d=stroke.points.map((p,i)=>`${i?'L':'M'} ${p.x-minX} ${p.y-minY}`).join(' ');return <svg className="stroke-preview" style={{left:minX,top:minY,width:Math.max(1,maxX-minX),height:Math.max(1,maxY-minY)}} viewBox={`0 0 ${Math.max(1,maxX-minX)} ${Math.max(1,maxY-minY)}`} preserveAspectRatio="none"><path d={d} fill="none" stroke="#f2f2f2" strokeWidth={stroke.style==='brush'?12:stroke.style==='pen'?2:4} strokeLinecap="round" strokeLinejoin="round"/></svg>}
function calculateSnap(m:Rect,targets:Rect[],t:number){const mx=[m.x,m.x+m.width/2,m.x+m.width],my=[m.y,m.y+m.height/2,m.y+m.height];let bx:{diff:number;target:Rect;pos:number}|null=null,by:{diff:number;target:Rect;pos:number}|null=null;for(const n of targets){for(const a of mx)for(const b of[n.x,n.x+n.width/2,n.x+n.width]){const d=b-a;if(Math.abs(d)<=t&&(!bx||Math.abs(d)<Math.abs(bx.diff)))bx={diff:d,target:n,pos:b}}for(const a of my)for(const b of[n.y,n.y+n.height/2,n.y+n.height]){const d=b-a;if(Math.abs(d)<=t&&(!by||Math.abs(d)<Math.abs(by.diff)))by={diff:d,target:n,pos:b}}}const guides:Guide[]=[];if(bx)guides.push({axis:'x',position:bx.pos,start:Math.min(m.y+(by?.diff??0),bx.target.y)-40,end:Math.max(m.y+m.height+(by?.diff??0),bx.target.y+bx.target.height)+40});if(by)guides.push({axis:'y',position:by.pos,start:Math.min(m.x+(bx?.diff??0),by.target.x)-40,end:Math.max(m.x+m.width+(bx?.diff??0),by.target.x+by.target.width)+40});return{dx:bx?.diff??0,dy:by?.diff??0,guides}}
function nearestMeasurements(s:Rect,targets:Rect[]):Measure[]{let l:any=null,r:any=null,t:any=null,b:any=null;for(const q of targets){if(verticalOverlap(s,q)){if(q.x+q.width<=s.x){const g=s.x-q.x-q.width;if(!l||g<l.gap)l={gap:g,rect:q}}if(q.x>=s.x+s.width){const g=q.x-s.x-s.width;if(!r||g<r.gap)r={gap:g,rect:q}}}if(horizontalOverlap(s,q)){if(q.y+q.height<=s.y){const g=s.y-q.y-q.height;if(!t||g<t.gap)t={gap:g,rect:q}}if(q.y>=s.y+s.height){const g=q.y-s.y-s.height;if(!b||g<b.gap)b={gap:g,rect:q}}}}const out:Measure[]=[];const h=[l,r].filter(Boolean).sort((a:any,b:any)=>a.gap-b.gap)[0];if(h){const q=h.rect;out.push(q.x<s.x?{axis:'x',start:q.x+q.width,end:s.x,cross:Math.max(s.y,q.y)+Math.min(s.height,q.height)/2,value:h.gap}:{axis:'x',start:s.x+s.width,end:q.x,cross:Math.max(s.y,q.y)+Math.min(s.height,q.height)/2,value:h.gap})}const v=[t,b].filter(Boolean).sort((a:any,b:any)=>a.gap-b.gap)[0];if(v){const q=v.rect;out.push(q.y<s.y?{axis:'y',start:q.y+q.height,end:s.y,cross:Math.max(s.x,q.x)+Math.min(s.width,q.width)/2,value:v.gap}:{axis:'y',start:s.y+s.height,end:q.y,cross:Math.max(s.x,q.x)+Math.min(s.width,q.width)/2,value:v.gap})}return out.filter(x=>x.value<=400)}
function parentMeasurements(s:Rect,p:Rect):Measure[]{const cx=s.x+s.width/2,cy=s.y+s.height/2;return[{axis:'x',start:p.x,end:s.x,cross:cy,value:Math.max(0,s.x-p.x)},{axis:'x',start:s.x+s.width,end:p.x+p.width,cross:cy,value:Math.max(0,p.x+p.width-s.x-s.width)},{axis:'y',start:p.y,end:s.y,cross:cx,value:Math.max(0,s.y-p.y)},{axis:'y',start:s.y+s.height,end:p.y+p.height,cross:cx,value:Math.max(0,p.y+p.height-s.y-s.height)}].filter(m=>m.value>.5) as Measure[]}
function GuideLine({guide:g,zoom}:{guide:Guide;zoom:number}){return g.axis==='x'?<div className="smart-guide" style={{left:g.position,top:g.start,height:g.end-g.start,width:1/zoom}}/>:<div className="smart-guide" style={{top:g.position,left:g.start,width:g.end-g.start,height:1/zoom}}/>}
function MeasureLine({measure:m,zoom}:{measure:Measure;zoom:number}){if(m.value<1)return null;return m.axis==='x'?<div className="measure-line measure-x" style={{left:m.start,top:m.cross,width:m.end-m.start,height:1/zoom}}><span style={{transform:`translate(-50%,-50%) scale(${1/zoom})`}}>{Math.round(m.value)} px</span></div>:<div className="measure-line measure-y" style={{left:m.cross,top:m.start,height:m.end-m.start,width:1/zoom}}><span style={{transform:`translate(-50%,-50%) scale(${1/zoom})`}}>{Math.round(m.value)} px</span></div>}
const round=(n:number)=>Math.round(n*100)/100
function isInput(t:EventTarget|null){const e=t as HTMLElement|null;return!!e&&(e.tagName==='INPUT'||e.tagName==='TEXTAREA'||e.isContentEditable)}

function nodeAtTime(node:CanvasNode,time:number):CanvasNode{const frames=[...(node.keyframes??[])].sort((a,b)=>a.time-b.time);if(!frames.length)return node;if(time<=frames[0].time)return {...node,...pickFrame(frames[0])};if(time>=frames[frames.length-1].time)return {...node,...pickFrame(frames[frames.length-1])};let a=frames[0],b=frames[frames.length-1];for(let i=0;i<frames.length-1;i++){if(time>=frames[i].time&&time<=frames[i+1].time){a=frames[i];b=frames[i+1];break}}const t=(time-a.time)/Math.max(1,b.time-a.time),lerp=(x:number,y:number)=>x+(y-x)*t;return {...node,x:lerp(a.x,b.x),y:lerp(a.y,b.y),width:lerp(a.width,b.width),height:lerp(a.height,b.height),rotation:lerp(a.rotation,b.rotation),opacity:lerp(a.opacity,b.opacity)}}
function pickFrame(k:{x:number;y:number;width:number;height:number;rotation:number;opacity:number}){return{x:k.x,y:k.y,width:k.width,height:k.height,rotation:k.rotation,opacity:k.opacity}}
