import { useEffect, useMemo, useState } from 'react'
import { useEditorStore } from '../store/editorStore'
import { rectUnion } from '../lib/geometry'
import type { CanvasNode, PrototypeInteraction } from '../types/editor'
import { ancestorIds, worldBounds, worldMatrix } from '../editor/scene/sceneGraph'

export function PreviewModal() {
  const open=useEditorStore(state=>state.previewOpen),close=useEditorStore(state=>state.setPreviewOpen),objects=useEditorStore(state=>state.objects),order=useEditorStore(state=>state.order),selected=useEditorStore(state=>state.selectedIds)
  const initialFrame=useMemo(()=>{for(const id of selected){if(objects[id]?.type==='frame')return id;const parent=ancestorIds(id,objects).find(parentId=>objects[parentId]?.type==='frame');if(parent)return parent}return order.find(id=>objects[id]?.type==='frame'&&!objects[id].parentId)??null},[selected,objects,order])
  const [frameId,setFrameId]=useState<string|null>(initialFrame),[stack,setStack]=useState<string[]>([]),[transition,setTransition]=useState<PrototypeInteraction['transition']>('instant')
  useEffect(()=>{if(open){setFrameId(initialFrame);setStack([]);setTransition('instant')}},[open,initialFrame])
  const nodes=useMemo(()=>{const ids=frameId?order.filter(id=>id===frameId||ancestorIds(id,objects).includes(frameId)):order;return ids.map(id=>objects[id]).filter((node):node is CanvasNode=>!!node&&node.visible)},[objects,order,frameId])
  const bounds=useMemo(()=>frameId&&objects[frameId]?worldBounds(frameId,objects):rectUnion(nodes.map(node=>worldBounds(node.id,objects))),[nodes,objects,frameId])
  const execute=(interaction?:PrototypeInteraction)=>{if(!interaction)return;if(interaction.action==='back'){const previous=stack[stack.length-1];if(previous){setStack(items=>items.slice(0,-1));setTransition(interaction.transition);setFrameId(previous)}return}if(interaction.action==='url'&&interaction.url){window.open(interaction.url,'_blank','noopener,noreferrer');return}if((interaction.action==='navigate'||interaction.action==='open-overlay')&&interaction.destinationId&&objects[interaction.destinationId]){if(frameId)setStack(items=>[...items,frameId]);setTransition(interaction.transition);setFrameId(interaction.destinationId)}}
  useEffect(()=>{if(!open)return;const delayed=nodes.find(node=>node.prototype?.trigger==='after-delay')?.prototype;if(!delayed)return;const timer=window.setTimeout(()=>execute(delayed),Math.max(0,delayed.delay??800));return()=>window.clearTimeout(timer)},[open,frameId,nodes])
  if(!open)return null
  return <div className="preview-overlay" role="dialog" aria-modal="true" aria-label="Просмотр проекта"><div className="preview-header"><strong>Прототип</strong><span>{frameId&&objects[frameId]?objects[frameId].name:selected.length?'Выбранные объекты':'Весь холст'}</span><div className="preview-nav">{stack.length>0&&<button onClick={()=>execute({trigger:'click',action:'back',transition:'slide-right',duration:250})}>← Назад</button>}<button onClick={()=>{setFrameId(initialFrame);setStack([])}}>↻ Сначала</button><button onClick={()=>close(false)}>Закрыть <kbd>Esc</kbd></button></div></div><div className="preview-stage"><div key={frameId??'all'} className={`preview-content transition-${transition}`} style={{width:Math.max(1,bounds.width),height:Math.max(1,bounds.height)}}>{nodes.map(node=><PreviewNode key={node.id} node={node} origin={bounds} execute={execute}/>)}</div></div></div>
}

function PreviewNode({node,origin,execute}:{node:CanvasNode;origin:{x:number;y:number};execute:(interaction?:PrototypeInteraction)=>void}) { const matrix=worldMatrix(node.id,useEditorStore.getState().objects),interaction=node.prototype,style={left:0,top:0,width:node.width,height:node.height,opacity:node.opacity,transformOrigin:'0 0',transform:`matrix(${matrix.a},${matrix.b},${matrix.c},${matrix.d},${matrix.e-origin.x},${matrix.f-origin.y})`,borderRadius:node.type==='ellipse'?'50%':node.radius,background:node.type==='text'||node.type==='image'||node.type==='path'||node.type==='group'?'transparent':node.fill,border:node.strokeWidth?`${node.strokeWidth}px solid ${node.stroke}`:'none',boxShadow:node.shadowEnabled?`${node.shadowX??0}px ${node.shadowY??4}px ${node.shadowBlur??12}px ${node.shadowColor??'#00000055'}`:undefined,cursor:interaction?'pointer':'default'} as const; return <div className="preview-node" style={style} onClick={event=>{if(interaction?.trigger==='click'){event.stopPropagation();execute(interaction)}}} onPointerEnter={()=>{if(interaction?.trigger==='hover')execute(interaction)}}>{node.type==='image'&&node.imageSrc&&<img src={node.imageSrc} alt=""/>}{(node.type==='text'||node.type==='sticky')&&<div className={`preview-text align-${node.textVerticalAlign??'top'}`} style={{fontFamily:node.fontFamily,fontSize:node.fontSize,fontWeight:node.fontWeight,lineHeight:node.lineHeight,letterSpacing:node.letterSpacing,textAlign:node.textAlign,textDecoration:node.textDecoration,textTransform:node.textTransform,padding:node.type==='sticky'?12:3}}>{node.text}</div>}{node.type==='path'&&<Path node={node}/>}</div> }
function Path({node}:{node:CanvasNode}) { const d=`${(node.path??[]).map((point,index)=>`${index?'L':'M'} ${point.x} ${point.y}`).join(' ')}${node.pathClosed?' Z':''}`; return <svg width="100%" height="100%" viewBox={`0 0 ${Math.max(1,node.width)} ${Math.max(1,node.height)}`} preserveAspectRatio="none"><path d={d} fill={node.pathClosed?node.fill:'none'} stroke={node.stroke} strokeWidth={node.strokeWidth} strokeLinecap={node.strokeCap??'round'} strokeLinejoin={node.strokeJoin??'round'}/></svg> }
